### ISSUE TITLE
It's a virus?

### ISSUE THREAD

**Issue by mohamedkoujil** [thewh1teagle/happy#2]
https://www.virustotal.com/gui/file/464059fac739e0b660b9031e55ac0172f22d2b391852215d0fc8825c3444efc5
Windows also detects it as a malicious app

**Comment by thewh1teagle** [comment]
It's not, maybe I used upx to compress the binary and thats cause false positive.
Anyway it's open source you can compile it and use your own binary

**Comment by mohamedkoujil** [comment]
Oh, thx for the replay. Surely its a false positive
