### ISSUE TITLE
PLEASE make a screen capture setting

### ISSUE THREAD

**Issue by PJREZ** [thewh1teagle/happy#3]
add a feature where it takes the colors on your screen, and using that, changes the colors of the screen

(if the screen is red, change to red, if blue change to blue etc)

**Comment by thewh1teagle** [comment]
@PJREZ 
What OS do you use?
Did it worked for you with the leds easily?

**Comment by PJREZ** [comment]
I use windows lol, thing is I know nothing about python, github, etc. The app works really good I just want this one feature lol


I just want the colors to match the music video I'm watching lol, any suggestions? do u have a discord?

**Comment by thewh1teagle** [comment]
Yes 527540023940349953

**Comment by PJREZ** [comment]
i'm sorry but idk what that number is lol

**Comment by thewh1teagle** [comment]
Just a sec I'm not used to discord

**Comment by thewh1teagle** [comment]
Maybe this one is my profile?
thewh1teagle

**Comment by PJREZ** [comment]
that worked, i sent it lol

**Comment by thewh1teagle** [comment]
Added in [1.0.3](https://github.com/thewh1teagle/happy/releases)

**Comment by PJREZ** [comment]
dude thank you so much, I aboslutely love it. the only issue I see with it, is that the color red doesn't show up very often. Maybe this is a bug, but everything is very blue, even when the screen is red

**Comment by thewh1teagle** [comment]
You welcome :)
I think that this issue is in the LEDs themself.
I tried to set it to RED color from happy light Android app, from red image, and 
it was the same, insead of red it was purple and even more blue / white
