### ISSUE TITLE
Brightness Slider

### ISSUE THREAD

**Issue by Marcel1138** [thewh1teagle/happy#4]
Hi,
Works perfectly, but
Where is the Brightness Slider? :D
Do you plan to add that?

**Comment by thewh1teagle** [comment]
Hello :)
You can control the brightness theoretically from the color picker, but currently there's no stand alone brightness slider.
I'm not planning currently to add it but if someone want to add it then contribution is welcome!

**Comment by tehnac420** [comment]
Great job first of all but can you please add a speed option for the different modes since the just go really fast
